### PR TITLE
Syntax issues on lines 07 & 115

### PR DESCRIPTION
**Pull request by kant**
### Description
Fixed typos on lines 7 & 115

### Related Issues
There is no related issue involved

### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jiata** [comment]
Hello kant, thank you for making this up. Could you switch your PR to merge into staging, then we'll get it merged in.

**Comment by kant** [comment]
@jiata Please, let me know the steps to be done to "_switch your PR to merge into staging_". As far as I know, I can only `PR` against `Master` branch...

**Comment by simonzhaoms** [comment]
@kant Hope it is helpful.

Screenshot from 2019-10-18 11-40-34

**Comment by kant** [comment]
@simonzhaoms @jiata Kudos for your asistance!

**Comment by jiata** [comment]
closing this since you have the other PR

**Pull request closed without merging**
