### PR TITLE
Use pathlib only in data.py

### PR DESCRIPTION
**Pull request by simonzhaoms**
### Checklist:

- [x] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by simonzhaoms** [comment]
I find `os.path` and `pathlib.Path` being used interchangeably in `utils_cv/common/data.py`.  Not sure if appropriate to use only one of them.  There are [many other places](https://github.com/microsoft/ComputerVision/search?q=pathlib&unscoped_q=pathlib) doing in this way.

**Comment by jiata** [comment]
> I find `os.path` and `pathlib.Path` being used interchangeably in `utils_cv/common/data.py`. Not sure if appropriate to use only one of them. There are [many other places](https://github.com/microsoft/ComputerVision/search?q=pathlib&unscoped_q=pathlib) doing in this way.

yeah maybe we should stick to pathlib.Path, as you do in your PR - seems more modern...

**Comment by PatrickBue** [comment]
@simonzhaoms Please only merge this after running our full tests on windows and on Linux. I have seen inconsistent behavior before, that's why. 
Fyi, currently our windows tests are failing, so that's a blocker but Miguel is working on it.

**Comment by PatrickBue** [comment]
Thanks for making this change. See my comment above and why we shouldn't merge this at the moment. Our devops testing pipeline is currently half broken. Miguel is working on it.

**Comment by jiata** [comment]
pathlib should be OS agnostic, but good idea to make sure tests pass!

https://pbpython.com/pathlib-intro.html
> "Pathlib is an object oriented interface to the filesystem and provides a more intuitive method to interact with the filesystem in a platform agnostic and pythonic manner."

**Comment by simonzhaoms** [comment]
Thank you.  Sure.  Just make sure we are aware of this.  And it is less error-prone.

**Pull request closed without merging**
