### PR TITLE
Correct unzipped file dest folder to unzipped_dir

### PR DESCRIPTION
**Pull request by simonzhaoms**
### Description

The function `unzip_url()` is used to download a zip file to `fpath / zip file` and unzip it to `dest / zip file without extension`, so the correct parameter for `ZipFile.extratcall()` needs to be `dest / zip file without extension` which is `unzipped_dir` in the code instead of `fpath`.

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jiata** [comment]
can you update the tests too?

**Comment by simonzhaoms** [comment]
> we need to update the tests too

OK, I will update related code

**Comment by simonzhaoms** [comment]
Updated

**Comment by simonzhaoms** [comment]
After discussion, we decide to keep the function as it is.

**Comment by PatrickBue** [comment]
@simonzhaoms Thanks for talking to JS and deciding on what the best way forward is!!

**Pull request closed without merging**
