### PR TITLE
reorganize coding guidelines 

### PR DESCRIPTION
**Pull request by jiata**
### Description
Move the coding guidelines from `classification/readme.md` to `CONTRIBUTING.md`

### Related Issues
One place for users to find all information regarding contribution standards.

### CODE REVIEW

**Comment by jiata** [comment]
i didnt touch any code in this PR but tests are failing  @jainr @bethz

**Comment by PatrickBue** [comment]
Hi! I am getting the same errors in my PR. Thought it has to do with changes I did in my code, but obviously your PRs should pass. What's even more weird is that the tests on https://github.com/microsoft/ComputerVision are all green and passing.
@jainr @bethz Any idea where this might be coming from?

**Comment by jiata** [comment]
> Hi! I am getting the same errors in my PR. Thought it has to do with changes I did in my code, but obviously your PRs should pass. What's even more weird is that the tests on https://github.com/microsoft/ComputerVision are all green and passing.
> @jainr @bethz Any idea where this might be coming from?

it looks like the machines that run the `unit-test-linux-gpu` pipeline is using an older version of python and failing on typehinting syntax, and the `azureml-notebook-test-linux-gpu` is failing because the kernel name is not being passed it.

**Comment by PatrickBue** [comment]
@miguel-ferreira  as fyi. Ignore the failing azureml-notebook-test-linux-cup pipeline. It's failing if two runs are happening at the same time (I took it out from PR triggering). The failing unit-test-linux-gpu pipeline is the problem, plus we should update some of the triggering (e.g. all tests should run nightly even if code didn't change but some of the dependencies might have)

**Pull request merged**
