### PR TITLE
if folder exists, remove

### PR DESCRIPTION
**Pull request by miguelgfierro**
### Description

I had a similar error in reco https://github.com/microsoft/recommenders/pull/985, right now your pipeline is not failing because you have `continueOnError` skip the error when the folder `cv` does not exist, however, the current pipeline won't detect if there is a different error. This change just check whether there is a folder called `cv` and then erase it

### Checklist:

- [ ] I have followed the [contribution guidelines](../CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions.
- [ ] I have updated the documentation accordingly.
- [ ] This PR is being made to `staging` and not `master`

### CODE REVIEW

**Comment by PatrickBue** [comment]
@miguelgfierro Hi Miguel! Do you want us to merge this for you?

**Comment by miguelgfierro** [comment]
yes, if you agree with the changes, please merge.

**Comment by PatrickBue** [comment]
@Jiata Can you sign off please if this looks good (lgtm)

**Comment by jiata** [comment]
yeah looks good. i'm going to merge this.

**Pull request merged**
